GET http://localhost:3333

###
POST http://localhost:3333/create
Content-Type: application/json

{
    "name": "a",
    "email": "as@123",
    "password": "123"
}

###
DELETE http://localhost:3333/delete/6